export const PLANT_EQUIPMENT_CATEGORIES = [
  'Two Pole Hoists',
  'Oil handling equipment',
  'Used Oil tank',
  'Waste oil handling equipment',
  'Hydraulic jacks',
  'Pneumatic Jacks',
  'Electric jacks',
  'Scissor jacks',
  'Four Pole Hoists',
  'Wheel Alignment equipment',
  'Tyre changer - LV',
  'Tyre Changer HGV',
  'Wheel balance LV',
  'Wheel balancer HGV',
  'Tricycle body manufacturing',
  'Truck body manufacturing',
  'Specialised vehicles conversion',
  'Mobile laboratory conversion',
  'Type A Ambulance conversion',
  'Type B Ambulance conversion',
  'Type C Ambulance conversion',
  'Ambulance Medical Command unit',
  'Mobile clinics conversion',
  'Mobile kitchens conversion',
  'Mobile cooking stations conversion',
  'Towable units conversion',
  'Mobile film trucks conversion',
  'Mobile workshop vans conversion',
  'Ferry building',
  'Boat building',
] as const;
